@extends('layouts.app')
@section('content')
    <div>
       <div>
        <search-component/>
        <firends-component/>
       </div>
       <div>
        <message-component/>
       </div>
    </div>
@endsection